[project]
name = "pdf-borehole-report-analyze"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pdfplumber>=0.11",
    "PyPDF2>=3.0",
]
